#
#   Файл конфигурации py2shauth
#

sms_service: # Настройки sms-центра
  login: 7908000000
  password: mygoodpassword 

extra:
  sec_code_min_len: 4 # Минимальное число символов для случайного пароля
  sec_code_max_len: 4 # Максимальное число символов для случайного пароля
  deny_access_for_none_user: True # Запрет доступа, в случае если юзер не определён в секции users.
  set_shell: /bin/bash # Шел, в который будет направлен юзер в случае успешной проверки.

users: # Пользователи
  saymon:
    phone: 7908000000
    exclude_ips: # Айпи адреса, для которых не будет происходить проверка дополнительного пароля.
      - 10.13.138.17
    exclude_nets: # Подсети, для которых не будет происходить проверка дополнительного пароля.
      - 192.168.56.0/24
