# Для пользователя u0031_saymon устанавливаем номер телефона 7908000000
# И разрешаем ему проходить аутентификацию без дополнительного пароля, 
# Если тот подключился с айпи адреса 10.13.138.17 или 192.168.56.0/24.
# Если исключения айпи адресов или масок сети не нужны, можно просто закоментировать. 
users: # Пользователи
  u0031_saymon:
    phone: 7908000000
#    exclude_ips: # Айпи адреса, для которых не будет происходить проверка дополнительного пароля.
#      - 10.13.138.17
#    exclude_nets: # Подсети, для которых не будет происходить проверка дополнительного пароля.
#      - 192.168.56.0/24
